name: visfusion
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9.16
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3.1
  - ipython
  - sparsehash # dependency for torchsparse
  - pip
  - pip:
    - ray
    - transforms3d
    - tqdm
    - opencv-python
    - numba
    - pycuda
    - tensorboardX
    - scikit-image
    - trimesh
    - yacs
    - h5py
    - loguru
    - pyrender
    - pyglet
    - open3d
    - git+https://github.com/mit-han-lab/torchsparse.git # torchsparse
    - https://github.com/JamieWatson683/scikit-image/archive/single_mesh.zip # single mesh for measure.marching_cubes