DATASET: 'scannet'
BATCH_SIZE: 2
SAVE_SCENE_MESH: False
LOGDIR: './checkpoints'
SAVE_FREQ: 1
MODE: 'train'

TRAIN:
  PATH: '/home/huiyu/Documents/Datasets2/ScanNet'
  EPOCHS: 99
  N_VIEWS: 9
  LR: 1e-3
  N_WORKERS: 6
  LREPOCHS: '12,24,48,52,56,60:2'
  FINETUNE_LAYER: None # choose None to train the whole model; choose 0, 1 or 2 to finetune a specific layer

TEST:
  PATH: '/home/huiyu/Documents/Datasets2/ScanNet'
  N_VIEWS: 9
  N_WORKERS: 4

MODEL:
  PASS_LAYERS: 2 # When finetune a specific layer, set PASS_LAYERS equal to TRAIN.FINETUNE_LAYER to save inference time.
  N_LAYER: 3
  N_VOX: [96, 96, 96]
  VOXEL_SIZE: 0.04
  TRAIN_NUM_SAMPLE: [4096, 16384, 65536]
  TEST_NUM_SAMPLE: [4096, 16384, 65536]

  BACKBONE2D:
    ARC: 'fpn-mnas-1'

  FUSION:
    FUSION_ON: True
    HIDDEN_DIM: 64
    SPARSIFY: "continuous_k"

  LW: [1.0, 0.8, 0.64]
  TOP_K_OCC: [9, 9, 9]
  THRESHOLDS: [0, 0, 0]
  POS_WEIGHT: 1.5
